/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: SDC PERFORMANCE™️ (https://sketchfab.com/3Duae)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/animated-robot-sdc-3d127f327a6c4033a32b810b5fb071ed
Title: Animated ROBOT SDC
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame, useThree  } from '@react-three/fiber'
import { a } from '@react-spring/three'

import isAnimatedrScene from '../assets/3d/animatedr.glb'

const AnimatedR = (props) => {
  const animatedrRef = useRef()
  const { nodes, materials, animations } = useGLTF(isAnimatedrScene)
  const { actions } = useAnimations(animations, animatedrRef)
  return (
    <a.group ref={animatedrRef} {...props}>
      <a.group name="Sketchfab_Scene">
        <a.group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <a.group name="root">
            <a.group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <a.group name="Armature_82" rotation={[0, 1.561, 0]}>
                <a.group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.Rubber}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <a.group name="Doigts_81" />
                </a.group>
              </a.group>
            </a.group>
          </a.group>
        </a.group>
      </a.group>
    </a.group>
  )
}

export default AnimatedR
