/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Mrlunettes (https://sketchfab.com/Mrlunettes)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robotic-empathy-3f8c728fa3b94676b4fc611d3af80e5a
Title: Robotic Empathy
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree  } from '@react-three/fiber'
import { a } from '@react-spring/three'

import isEmpathyrScene from '../assets/3d/empathyr.glb'

const EmpathyR = (props) => {
  const empathyrRef = useRef()
  const { nodes, materials } = useGLTF(isEmpathyrScene)
  return (
    <a.group ref={empathyrRef} {...props}>
      <a.group scale={0.01}>
        <a.group
          position={[10.105, 430.51, 0]}
          rotation={[-Math.PI / 2, 0.149, -Math.PI]}
          scale={100}>
          <mesh
            geometry={nodes.Cylinder012_Flex_0.geometry}
            material={materials.Flex}
          />
          <mesh
            geometry={nodes.Cylinder012_chrome_0.geometry}
            material={materials.chrome}
          />
        </a.group>
        <a.group
          position={[0.749, 375.369, -66.985]}
          rotation={[-1.435, -0.83, -2.958]}
          scale={[62.946, 62.946, 95.516]}>
          <mesh
            geometry={nodes['Cylinder017_Metal_fonc��_0'].geometry}
            material={materials.Metal_fonc}
          />
          <mesh
            geometry={nodes.Cylinder017_metal_blanc_0.geometry}
            material={materials.metal_blanc}
          />
          <mesh
            geometry={nodes.Cylinder017_Flex_0.geometry}
            material={materials.Flex}
          />
          <mesh
            geometry={nodes.Cylinder017_Metal_color_0.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.Cylinder017_LED_BLEU_0.geometry}
            material={materials.LED_BLEU}
          />
        </a.group>
        <a.group
          position={[35.728, 200.842, -45.463]}
          rotation={[-Math.PI / 2, 0, -2.941]}
          scale={[100, 100, 94.425]}>
          <mesh
            geometry={nodes.Cylinder009_metal_blanc_0.geometry}
            material={materials.metal_blanc}
          />
          <mesh
            geometry={nodes.Cylinder009_Metal_color_0.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes['Cylinder009_Metal_fonc��_0'].geometry}
            material={materials.Metal_fonc}
          />
          <mesh
            geometry={nodes.Cylinder009_LED_BLEU_0.geometry}
            material={materials.LED_BLEU}
          />
        </a.group>
        <a.group
          position={[-26.313, 200.842, 37.043]}
          rotation={[-Math.PI / 2, 0, 2.355]}
          scale={[100, 100, 94.425]}>
          <mesh
            geometry={nodes['Cylinder019_Metal_fonc��_0'].geometry}
            material={materials.Metal_fonc}
          />
          <mesh
            geometry={nodes.Cylinder019_Metal_color_0.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.Cylinder019_metal_blanc_0.geometry}
            material={materials.metal_blanc}
          />
          <mesh
            geometry={nodes.Cylinder019_LED_BLEU_0.geometry}
            material={materials.LED_BLEU}
          />
        </a.group>
        <a.group
          position={[126.692, 267.64, -139.188]}
          rotation={[-1.476, -1.158, 0.544]}
          scale={100}>
          <mesh
            geometry={nodes.Sphere004_Pied_0.geometry}
            material={materials.Pied}
          />
          <mesh
            geometry={nodes.Sphere004_LED_BLEU_0.geometry}
            material={materials.LED_BLEU}
          />
        </a.group>
        <a.group
          position={[0.515, 211.151, 127.525]}
          rotation={[-Math.PI / 2, 0, -2.244]}
          scale={39.693}>
          <mesh
            geometry={nodes.Cylinder010_Metal_color_0.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.Cylinder010_metal_blanc_0.geometry}
            material={materials.metal_blanc}
          />
          <mesh
            geometry={nodes.Cylinder010_Flex_0.geometry}
            material={materials.Flex}
          />
          <mesh
            geometry={nodes.Cylinder010_Pied_0.geometry}
            material={materials.Pied}
          />
          <mesh
            geometry={nodes.Cylinder010_LED_BLEU_0.geometry}
            material={materials.LED_BLEU}
          />
        </a.group>
        <a.group
          position={[116.418, 271.219, -138.27]}
          rotation={[-1.338, -1.131, -2.856]}
          scale={[62.946, 62.946, 95.516]}>
          <mesh
            geometry={nodes.Cylinder022_Metal_color_0.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.Cylinder022_metal_blanc_0.geometry}
            material={materials.metal_blanc}
          />
          <mesh
            geometry={nodes.Cylinder022_Flex_0.geometry}
            material={materials.Flex}
          />
          <mesh
            geometry={nodes.Cylinder022_Pied_0.geometry}
            material={materials.Pied}
          />
          <mesh
            geometry={nodes.Cylinder022_LED_BLEU_0.geometry}
            material={materials.LED_BLEU}
          />
        </a.group>
        <a.group position={[-61.612, 389.25, -0.01]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            geometry={nodes.Cube001_metal_blanc_0.geometry}
            material={materials.metal_blanc}
          />
          <mesh
            geometry={nodes.Cube001_Pied_0.geometry}
            material={materials.Pied}
          />
          <mesh
            geometry={nodes['Cube001_Metal_fonc��_0'].geometry}
            material={materials.Metal_fonc}
          />
          <mesh
            geometry={nodes.Cube001_Metal_color_0.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.Cube001_LED_BLANC_0.geometry}
            material={materials.LED_BLANC}
          />
          <mesh
            geometry={nodes.Cube001_LED_BLEU_0.geometry}
            material={materials.LED_BLEU}
          />
        </a.group>
        <a.group position={[-61.68, 389.25, -0.01]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            geometry={nodes.Cube002_Metal_color_0.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.Cube002_metal_blanc_0.geometry}
            material={materials.metal_blanc}
          />
        </a.group>
        <a.group position={[-12.983, 247.15, 0]} rotation={[-Math.PI / 2, 0.149, 0]} scale={100}>
          <mesh
            geometry={nodes.Sphere005_metal_blanc_0.geometry}
            material={materials.metal_blanc}
          />
          <mesh
            geometry={nodes['Sphere005_Metal_fonc��_0'].geometry}
            material={materials.Metal_fonc}
          />
          <mesh
            geometry={nodes.Sphere005_Metal_color_0.geometry}
            material={materials.material_0}
          />
        </a.group>
        <a.group
          position={[10.105, 430.51, 0]}
          rotation={[-Math.PI / 2, 0.149, -Math.PI]}
          scale={100}>
          <mesh
            geometry={nodes.Cylinder011_Flex_0.geometry}
            material={materials.Flex}
          />
          <mesh
            geometry={nodes.Cylinder011_chrome_0.geometry}
            material={materials.chrome}
          />
        </a.group>
        <a.group position={[0, -6.029, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            geometry={nodes.Sphere007_Flex_0.geometry}
            material={materials.Flex}
          />
          <mesh
            geometry={nodes.Sphere007_LED_BLEU_0.geometry}
            material={materials.LED_BLEU}
          />
          <mesh
            geometry={nodes['Sphere007_Metal_fonc��_0'].geometry}
            material={materials.Metal_fonc}
          />
          <mesh
            geometry={nodes.Sphere007_metal_blanc_0.geometry}
            material={materials.metal_blanc}
          />
          <mesh
            geometry={nodes.Sphere007_Metal_color_0.geometry}
            material={materials.material_0}
          />
        </a.group>
        <mesh
          geometry={nodes.Cylinder001_Flex_0.geometry}
          material={materials.Flex}
          position={[-8.859, 246.453, 0]}
          rotation={[-Math.PI / 2, -0.083, -Math.PI]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cylinder002_tRONC_0.geometry}
          material={materials.tRONC}
          position={[-7.365, 246.453, 0]}
          rotation={[-1.628, -0.159, 2.796]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cylinder003_Flex_0.geometry}
          material={materials.Flex}
          position={[6.89, 201.283, -22.633]}
          rotation={[-1.186, -0.388, 2.946]}
          scale={[13.483, 13.483, 10.679]}
        />
        <mesh
          geometry={nodes.Plane001_Flex_0.geometry}
          material={materials.Flex}
          position={[126.692, 267.64, -139.188]}
          rotation={[1.373, -1.216, 1.506]}
          scale={100}
        />
        <mesh
          geometry={nodes.Plane002_Flex_0.geometry}
          material={materials.Flex}
          position={[126.692, 267.64, -139.188]}
          rotation={[-0.339, -1.389, -0.001]}
          scale={100}
        />
        <mesh
          geometry={nodes.Plane003_Flex_0.geometry}
          material={materials.Flex}
          position={[126.692, 267.64, -139.188]}
          rotation={[0.874, -1.007, 0.841]}
          scale={100}
        />
        <mesh
          geometry={nodes.Plane004_Flex_0.geometry}
          material={materials.Flex}
          position={[126.692, 267.64, -139.188]}
          rotation={[-1.476, -1.158, -1.103]}
          scale={100}
        />
        <mesh
          geometry={nodes.Sphere006_Flex_0.geometry}
          material={materials.Flex}
          position={[-12.983, 247.15, 0]}
          rotation={[-Math.PI / 2, 0.149, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cylinder020_Flex_0.geometry}
          material={materials.Flex}
          position={[0.515, 207.713, 127.525]}
          rotation={[-Math.PI / 2, 0, -2.244]}
          scale={21.06}
        />
        <mesh
          geometry={nodes.Sphere008_chrome_0.geometry}
          material={materials.chrome}
          position={[0, -6.029, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Sphere003_Pied_0.geometry}
          material={materials.Pied}
          position={[0.515, 211.151, 127.525]}
          rotation={[-Math.PI / 2, 0, 0.897]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cylinder021_Flex_0.geometry}
          material={materials.Flex}
          position={[0.749, 372.053, -65.341]}
          rotation={[-1.391, -0.965, -2.924]}
          scale={[62.946, 62.946, 108.177]}
        />
        <mesh
          geometry={nodes.Plane005_Flex_0.geometry}
          material={materials.Flex}
          position={[0.515, 211.151, 127.525]}
          rotation={[-Math.PI / 2, 0, 0.897]}
          scale={100}
        />
        <mesh
          geometry={nodes.Plane006_Flex_0.geometry}
          material={materials.Flex}
          position={[0.515, 211.151, 127.525]}
          rotation={[-Math.PI / 2, 0, 0.897]}
          scale={100}
        />
        <mesh
          geometry={nodes.Plane007_Flex_0.geometry}
          material={materials.Flex}
          position={[0.515, 211.151, 127.525]}
          rotation={[-Math.PI / 2, 0, 0.897]}
          scale={100}
        />
        <mesh
          geometry={nodes.Plane008_Flex_0.geometry}
          material={materials.Flex}
          position={[0.515, 211.151, 127.525]}
          rotation={[-Math.PI / 2, 0, 0.897]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cylinder004_Flex_0.geometry}
          material={materials.Flex}
          position={[-21.781, 197.323, 41.09]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes['Plane009_Metal_fonc��_0'].geometry}
          material={materials.Metal_fonc}
          position={[-76.889, 327.328, 37.975]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube003_Pied_0.geometry}
          material={materials.Pied}
          position={[-61.68, 389.25, -0.01]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cylinder005_eye_led_0.geometry}
          material={materials.eye_led}
          position={[10.105, 430.51, 0]}
          rotation={[-Math.PI / 2, 0.149, -Math.PI]}
          scale={100}
        />
        <mesh
          geometry={nodes.Sphere002_Flex_0.geometry}
          material={materials.Flex}
          position={[-12.983, 247.15, 0]}
          rotation={[-Math.PI / 2, 0.149, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cylinder006_tRONC_0.geometry}
          material={materials.tRONC}
          position={[-7.365, 246.453, 0]}
          rotation={[-1.628, -0.159, 2.796]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cylinder007_tRONC_0.geometry}
          material={materials.tRONC}
          position={[-7.365, 246.453, 0]}
          rotation={[-1.628, -0.159, 2.796]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cylinder013_GLASS_0.geometry}
          material={materials.GLASS}
          position={[10.105, 430.51, 0]}
          rotation={[-Math.PI / 2, 0.149, -Math.PI]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cylinder014_Flex_0.geometry}
          material={materials.Flex}
          position={[10.105, 430.51, 0]}
          rotation={[-Math.PI / 2, 0.149, -Math.PI]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cylinder016_NOIR_PROFOND_0.geometry}
          material={materials.NOIR_PROFOND}
          position={[10.105, 430.51, 0]}
          rotation={[-Math.PI / 2, 0.149, -Math.PI]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cylinder018_chrome_0.geometry}
          material={materials.chrome}
          position={[0.749, 375.369, -66.985]}
          rotation={[-1.435, -0.83, -2.958]}
          scale={[62.946, 62.946, 95.516]}
        />
        <mesh
          geometry={nodes.Cylinder023_LED_BLEU_0.geometry}
          material={materials.LED_BLEU}
          position={[0.749, 375.369, -66.985]}
          rotation={[-1.435, -0.83, -2.958]}
          scale={[62.946, 62.946, 95.516]}
        />
        <mesh
          geometry={nodes.Cylinder024_Pied_0.geometry}
          material={materials.Pied}
          position={[35.728, 200.842, -45.463]}
          rotation={[-Math.PI / 2, 0, -2.941]}
          scale={[100, 100, 94.425]}
        />
        <mesh
          geometry={nodes.Cylinder025_Pied_0.geometry}
          material={materials.Pied}
          position={[-26.313, 200.842, 37.043]}
          rotation={[-Math.PI / 2, 0, 2.355]}
          scale={[100, 100, 94.425]}
        />
        <mesh
          geometry={nodes.Sphere009_LED_BLEU_0.geometry}
          material={materials.LED_BLEU}
          position={[0, -6.029, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes['Plane010_Metal_fonc��_0'].geometry}
          material={materials.Metal_fonc}
          position={[-76.889, 327.328, 37.975]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes['Plane011_Metal_fonc��_0'].geometry}
          material={materials.Metal_fonc}
          position={[-76.889, 327.328, 37.975]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes['Plane012_Metal_fonc��_0'].geometry}
          material={materials.Metal_fonc}
          position={[-76.889, 327.328, 37.975]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes['Plane013_Metal_fonc��_0'].geometry}
          material={materials.Metal_fonc}
          position={[-76.889, 327.328, 37.975]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes['Plane014_Metal_fonc��_0'].geometry}
          material={materials.Metal_fonc}
          position={[-76.889, 327.328, 37.975]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes['Plane015_Metal_fonc��_0'].geometry}
          material={materials.Metal_fonc}
          position={[-76.889, 327.328, 37.975]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes['Plane016_Metal_fonc��_0'].geometry}
          material={materials.Metal_fonc}
          position={[-76.889, 327.328, 37.975]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes['Plane017_Metal_fonc��_0'].geometry}
          material={materials.Metal_fonc}
          position={[-76.889, 327.328, 37.975]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes['Plane018_Metal_fonc��_0'].geometry}
          material={materials.Metal_fonc}
          position={[-76.889, 327.328, 37.975]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes['Plane019_Metal_fonc��_0'].geometry}
          material={materials.Metal_fonc}
          position={[-76.889, 327.328, 37.975]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes['Plane020_Metal_fonc��_0'].geometry}
          material={materials.Metal_fonc}
          position={[-76.889, 327.328, 37.975]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes['Plane021_Metal_fonc��_0'].geometry}
          material={materials.Metal_fonc}
          position={[-76.889, 327.328, 37.975]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes['Plane022_Metal_fonc��_0'].geometry}
          material={materials.Metal_fonc}
          position={[-76.889, 327.328, 37.975]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes['Plane023_Metal_fonc��_0'].geometry}
          material={materials.Metal_fonc}
          position={[-76.889, 327.328, 37.975]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes['Plane024_Metal_fonc��_0'].geometry}
          material={materials.Metal_fonc}
          position={[-76.889, 327.328, 37.975]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube004_Pied_0.geometry}
          material={materials.Pied}
          position={[-61.68, 389.25, -0.01]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube005_Pied_0.geometry}
          material={materials.Pied}
          position={[-61.68, 389.25, -0.01]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube006_Pied_0.geometry}
          material={materials.Pied}
          position={[-61.68, 389.25, -0.01]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube007_Pied_0.geometry}
          material={materials.Pied}
          position={[-61.68, 389.25, -0.01]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube008_Pied_0.geometry}
          material={materials.Pied}
          position={[-61.68, 389.25, -0.01]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube009_Pied_0.geometry}
          material={materials.Pied}
          position={[-61.68, 389.25, -0.01]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube010_Pied_0.geometry}
          material={materials.Pied}
          position={[-61.68, 389.25, -0.01]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cylinder026_eye_led_0.geometry}
          material={materials.eye_led}
          position={[10.105, 430.51, 0]}
          rotation={[-Math.PI / 2, 0.149, -Math.PI]}
          scale={100}
        />
      </a.group>
    </a.group>
  )
}

export default EmpathyR
