/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: pinguinoconpulgares (https://sketchfab.com/pinguinoconpulgares)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/animated-humanoid-robot-8993602ca91f4c499e690e5dae19f978
Title: Animated humanoid robot
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame, useThree  } from '@react-three/fiber'
import { a } from '@react-spring/three'

import isHumanoidScene from '../assets/3d/humanoid.glb'

const Humanoid = (props) => {
  const humanoidRef = useRef()
  const { nodes, materials, animations } = useGLTF(isHumanoidScene)
  const { actions } = useAnimations(animations, humanoidRef)
  return (
    <a.group ref={humanoidRef} {...props}>
      <a.group name="Sketchfab_Scene">
        <a.group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <a.group name="Root">
            <a.group name="Hemi001" position={[13.036, -0.406, 4.759]}>
              <a.group name="Hemi001_1" />
            </a.group>
            <a.group
              name="Hemi002"
              position={[11.442, 2.03, -4.351]}
              rotation={[-Math.PI, 0, -Math.PI]}>
              <a.group name="Hemi002_1" />
            </a.group>
            <a.group name="ROBOT_BONES" position={[0.009, -3.516, 12.199]}>
              <primitive object={nodes.ROBOT_BONES_rootJoint} />
              <skinnedMesh
                name="Cylinder001"
                geometry={nodes.Cylinder001.geometry}
                material={materials.HEAD}
                skeleton={nodes.Cylinder001.skeleton}
              />
              <skinnedMesh
                name="Cylinder001_1"
                geometry={nodes.Cylinder001_1.geometry}
                material={materials.EYES}
                skeleton={nodes.Cylinder001_1.skeleton}
              />
              <skinnedMesh
                name="Cylinder001_2"
                geometry={nodes.Cylinder001_2.geometry}
                material={materials.BODY}
                skeleton={nodes.Cylinder001_2.skeleton}
              />
              <skinnedMesh
                name="Cylinder001_3"
                geometry={nodes.Cylinder001_3.geometry}
                material={materials.HINGE}
                skeleton={nodes.Cylinder001_3.skeleton}
              />
              <skinnedMesh
                name="Cylinder001_4"
                geometry={nodes.Cylinder001_4.geometry}
                material={materials.material}
                skeleton={nodes.Cylinder001_4.skeleton}
              />
              <skinnedMesh
                name="Cylinder001_5"
                geometry={nodes.Cylinder001_5.geometry}
                material={materials.material_5}
                skeleton={nodes.Cylinder001_5.skeleton}
              />
              <a.group
                name="Cylinder001_6"
                position={[-0.009, -0.165, -3.001]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.855}
              />
            </a.group>
          </a.group>
        </a.group>
      </a.group>
    </a.group>
  )
}

export default Humanoid
