/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: TiZeta (https://sketchfab.com/TiZeta)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kids-avatars-22ec160c6b594b4bb35aa503f945dbbd
Title: Kids (avatars)
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame, useThree  } from '@react-three/fiber'
import { a } from '@react-spring/three'

import isKidsScene from '../assets/3d/kids.glb'

const Kids = (props) => {
  const kidsRef = useRef()
  const { nodes, materials, animations } = useGLTF(isKidsScene)
  const { actions } = useAnimations(animations, kidsRef)
  return (
    <a.group ref={kidsRef} {...props}>
      <a.group name="Sketchfab_Scene">
        <a.group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <a.group name="Root">
            <a.group name="FLOOR" position={[0.001, 0.139, -0.065]} scale={[3.574, 3.574, 0.715]}>
              <mesh
                name="FLOOR_0" 
                geometry={nodes.FLOOR_0.geometry}
                material={materials['Material.001']}
              />
            </a.group>
            <a.group name="ARMATURE_D" position={[2.211, 0, 0]} rotation={[0, 0, -0.099]}>
              <primitive object={nodes.ARMATURE_D_rootJoint} />
              <skinnedMesh
                name="KID_D_0"
                geometry={nodes.KID_D_0.geometry}
                material={materials['Material.001']}
                skeleton={nodes.KID_D_0.skeleton}
              />
              <a.group name="KID_D" />
            </a.group>
            <a.group name="Lamp" position={[-1.82, -4.739, 5.904]} rotation={[1.06, 0.138, 0.646]}>
              <a.group name="Lamp_1" />
            </a.group>
          </a.group>
        </a.group>
      </a.group>
    </a.group>
  )
}

export default Kids
