/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Sobolev_Maxim (https://sketchfab.com/Sobolev_Maxim)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robot-police-little-helper-de4014cdb8f14cbd9aa1f294ae259a8d
Title: Robot Police Little Helper
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree  } from '@react-three/fiber'

import isPolicerScene from '../assets/3d/policer.glb'

const PoliceR = (props) => {
  const policerRef = useRef()
  const { nodes, materials } = useGLTF('/robot_police_little_helper.glb')
  return (
    <a.group ref={policerRef} {...props}>
      <a.group
        position={[0, -103.805, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[67.61, 67.61, 9.144]}>
        <mesh
          geometry={nodes['Cylinder001_plastic-main_0'].geometry}
          material={materials['plastic-main']}
        />
        <mesh
          geometry={nodes['Cylinder001_plastic-secondary_0'].geometry}
          material={materials['plastic-secondary']}
        />
        <mesh
          geometry={nodes['Cylinder001_plastic-dark_0'].geometry}
          material={materials['plastic-dark']}
        />
      </a.group>
      <a.group position={[0, 84.927, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes['Cylinder027_plastic-main-2_0'].geometry}
          material={materials['plastic-main-2']}
        />
        <mesh
          geometry={nodes['Cylinder027_plastic-dark_0'].geometry}
          material={materials['plastic-dark']}
        />
      </a.group>
      <a.group
        position={[57.575, -186.852, 55.358]}
        rotation={[-1.339, 0.229, 0.76]}
        scale={[117.409, 100, 100]}>
        <mesh
          geometry={nodes['Cube003_dark-metall_0'].geometry}
          material={materials['dark-metall']}
        />
        <mesh
          geometry={nodes.Cube003_chrome_0.geometry}
          material={materials.chrome}
        />
      </a.group>
      <a.group
        position={[56.333, -186.852, -56.621]}
        rotation={[-1.802, 0.23, 2.367]}
        scale={[117.409, 100, 100]}>
        <mesh
          geometry={nodes['Cube004_dark-metall_0'].geometry}
          material={materials['dark-metall']}
        />
        <mesh
          geometry={nodes.Cube004_chrome_0.geometry}
          material={materials.chrome}
        />
      </a.group>
      <a.group
        position={[-55.18, -186.852, -57.746]}
        rotation={[-1.812, -0.219, -2.424]}
        scale={[117.409, 100, 100]}>
        <mesh
          geometry={nodes['Cube005_dark-metall_0'].geometry}
          material={materials['dark-metall']}
        />
        <mesh
          geometry={nodes.Cube005_chrome_0.geometry}
          material={materials.chrome}
        />
      </a.group>
      <a.group
        position={[-54.423, -186.852, 58.46]}
        rotation={[-1.332, -0.222, -0.742]}
        scale={[117.409, 100, 100]}>
        <mesh
          geometry={nodes['Cube006_dark-metall_0'].geometry}
          material={materials['dark-metall']}
        />
        <mesh
          geometry={nodes.Cube006_chrome_0.geometry}
          material={materials.chrome}
        />
      </a.group>
      <a.group position={[89.899, -155.118, 87.271]} rotation={[0.222, 0.774, -0.158]} scale={100}>
        <mesh
          geometry={nodes['Cylinder008_dark-metall_0'].geometry}
          material={materials['dark-metall']}
        />
        <mesh
          geometry={nodes.Cylinder008_chrome_0.geometry}
          material={materials.chrome}
        />
      </a.group>
      <a.group
        position={[43.63, -144.709, 41.598]}
        rotation={[-Math.PI, 0.779, Math.PI / 2]}
        scale={[12.087, 12.087, 4.91]}>
        <mesh
          geometry={nodes.Cylinder011_chrome_0.geometry}
          material={materials.chrome}
        />
        <mesh
          geometry={nodes['Cylinder011_dark-metall_0'].geometry}
          material={materials['dark-metall']}
        />
      </a.group>
      <a.group position={[49.759, -168.163, 47.649]} rotation={[-1.862, -0.283, 0.75]} scale={100}>
        <mesh
          geometry={nodes['Cylinder012_dark-metall_0'].geometry}
          material={materials['dark-metall']}
        />
        <mesh
          geometry={nodes.Cylinder012_chrome_0.geometry}
          material={materials.chrome}
        />
      </a.group>
      <a.group
        position={[33.515, -133.453, 31.617]}
        rotation={[-Math.PI / 2, 0, 0.792]}
        scale={[27.262, 27.262, 10.258]}>
        <mesh
          geometry={nodes['Cylinder013_plastic-secondary_0'].geometry}
          material={materials['plastic-secondary']}
        />
        <mesh
          geometry={nodes['Cylinder013_plastic-dark_0'].geometry}
          material={materials['plastic-dark']}
        />
        <mesh
          geometry={nodes['Cylinder013_dark-metall_0'].geometry}
          material={materials['dark-metall']}
        />
      </a.group>
      <a.group position={[88.793, -155.118, -88.396]} rotation={[2.916, 0.789, -2.981]} scale={100}>
        <mesh
          geometry={nodes['Cylinder014_dark-metall_0'].geometry}
          material={materials['dark-metall']}
        />
        <mesh
          geometry={nodes.Cylinder014_chrome_0.geometry}
          material={materials.chrome}
        />
      </a.group>
      <a.group
        position={[42.337, -144.709, -42.913]}
        rotation={[Math.PI, -0.775, Math.PI / 2]}
        scale={[12.087, 12.087, 4.91]}>
        <mesh
          geometry={nodes.Cylinder017_chrome_0.geometry}
          material={materials.chrome}
        />
        <mesh
          geometry={nodes['Cylinder017_dark-metall_0'].geometry}
          material={materials['dark-metall']}
        />
      </a.group>
      <a.group position={[48.491, -168.163, -48.938]} rotation={[-1.28, -0.284, 2.388]} scale={100}>
        <mesh
          geometry={nodes['Cylinder018_dark-metall_0'].geometry}
          material={materials['dark-metall']}
        />
        <mesh
          geometry={nodes.Cylinder018_chrome_0.geometry}
          material={materials.chrome}
        />
      </a.group>
      <a.group
        position={[32.184, -133.453, -32.971]}
        rotation={[-Math.PI / 2, 0, 2.346]}
        scale={[27.262, 27.262, 10.258]}>
        <mesh
          geometry={nodes['Cylinder019_plastic-secondary_0'].geometry}
          material={materials['plastic-secondary']}
        />
        <mesh
          geometry={nodes['Cylinder019_plastic-dark_0'].geometry}
          material={materials['plastic-dark']}
        />
        <mesh
          geometry={nodes['Cylinder019_dark-metall_0'].geometry}
          material={materials['dark-metall']}
        />
      </a.group>
      <a.group position={[-86.124, -155.118, -90.999]} rotation={[2.928, -0.733, 2.996]} scale={100}>
        <mesh
          geometry={nodes['Cylinder020_dark-metall_0'].geometry}
          material={materials['dark-metall']}
        />
        <mesh
          geometry={nodes.Cylinder020_chrome_0.geometry}
          material={materials.chrome}
        />
      </a.group>
      <a.group
        position={[-41.83, -144.709, -43.407]}
        rotation={[0, -0.821, -Math.PI / 2]}
        scale={[12.087, 12.087, 4.91]}>
        <mesh
          geometry={nodes.Cylinder023_chrome_0.geometry}
          material={materials.chrome}
        />
        <mesh
          geometry={nodes['Cylinder023_dark-metall_0'].geometry}
          material={materials['dark-metall']}
        />
      </a.group>
      <a.group position={[-47.697, -168.163, -49.712]} rotation={[-1.268, 0.271, -2.434]} scale={100}>
        <mesh
          geometry={nodes['Cylinder024_dark-metall_0'].geometry}
          material={materials['dark-metall']}
        />
        <mesh
          geometry={nodes.Cylinder024_chrome_0.geometry}
          material={materials.chrome}
        />
      </a.group>
      <a.group
        position={[-32.147, -133.453, -33.007]}
        rotation={[-Math.PI / 2, 0, -2.392]}
        scale={[27.262, 27.262, 10.258]}>
        <mesh
          geometry={nodes['Cylinder025_plastic-secondary_0'].geometry}
          material={materials['plastic-secondary']}
        />
        <mesh
          geometry={nodes['Cylinder025_plastic-dark_0'].geometry}
          material={materials['plastic-dark']}
        />
        <mesh
          geometry={nodes['Cylinder025_dark-metall_0'].geometry}
          material={materials['dark-metall']}
        />
      </a.group>
      <a.group position={[-93.401, -182.542, 93.339]} rotation={[1.23, -1.093, 0.317]} scale={100}>
        <mesh
          geometry={nodes['Cylinder026_dark-metall_0'].geometry}
          material={materials['dark-metall']}
        />
        <mesh
          geometry={nodes.Cylinder026_chrome_0.geometry}
          material={materials.chrome}
        />
      </a.group>
      <a.group position={[0, 8.254, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes['Cylinder028_plastic-main-2_0'].geometry}
          material={materials['plastic-main-2']}
        />
        <mesh
          geometry={nodes['Cylinder028_plastic-secondary_0'].geometry}
          material={materials['plastic-secondary']}
        />
        <mesh
          geometry={nodes['Cylinder028_plastic-dark_0'].geometry}
          material={materials['plastic-dark']}
        />
      </a.group>
      <a.group
        position={[-40.889, -144.709, 44.295]}
        rotation={[0, 0.808, -Math.PI / 2]}
        scale={[12.087, 12.087, 4.91]}>
        <mesh
          geometry={nodes.Cylinder038_chrome_0.geometry}
          material={materials.chrome}
        />
        <mesh
          geometry={nodes['Cylinder038_dark-metall_0'].geometry}
          material={materials['dark-metall']}
        />
      </a.group>
      <a.group position={[-46.84, -168.163, 50.521]} rotation={[-1.87, 0.275, -0.721]} scale={100}>
        <mesh
          geometry={nodes['Cylinder044_dark-metall_0'].geometry}
          material={materials['dark-metall']}
        />
        <mesh
          geometry={nodes.Cylinder044_chrome_0.geometry}
          material={materials.chrome}
        />
      </a.group>
      <a.group
        position={[-31.072, -133.453, 34.021]}
        rotation={[-Math.PI / 2, 0, -0.763]}
        scale={[27.262, 27.262, 10.258]}>
        <mesh
          geometry={nodes['Cylinder045_plastic-secondary_0'].geometry}
          material={materials['plastic-secondary']}
        />
        <mesh
          geometry={nodes['Cylinder045_plastic-dark_0'].geometry}
          material={materials['plastic-dark']}
        />
        <mesh
          geometry={nodes['Cylinder045_dark-metall_0'].geometry}
          material={materials['dark-metall']}
        />
      </a.group>
      <a.group position={[0, 168.454, 0]} rotation={[-Math.PI / 2, 0, -0.494]} scale={18.532}>
        <mesh
          geometry={nodes.Cylinder046_chrome_0.geometry}
          material={materials.chrome}
        />
        <mesh
          geometry={nodes['Cylinder046_dark-metall_0'].geometry}
          material={materials['dark-metall']}
        />
      </a.group>
      <a.group position={[0, 7.088, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes['Cylinder048_plastic-dark_0'].geometry}
          material={materials['plastic-dark']}
        />
        <mesh
          geometry={nodes['Cylinder048_plastic-secondary_0'].geometry}
          material={materials['plastic-secondary']}
        />
      </a.group>
      <a.group position={[0, 7.897, 1.501]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes['Cylinder049_plastic-main_0'].geometry}
          material={materials['plastic-main']}
        />
        <mesh
          geometry={nodes['Cylinder049_plastic-dark_0'].geometry}
          material={materials['plastic-dark']}
        />
        <mesh
          geometry={nodes['Cylinder049_plastic-secondary_0'].geometry}
          material={materials['plastic-secondary']}
        />
        <mesh
          geometry={nodes['Cylinder049_plastic-dark-dark_0'].geometry}
          material={materials['plastic-dark-dark']}
        />
      </a.group>
      <a.group
        position={[0, 7.897, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[101.054, 101.054, 100]}>
        <mesh
          geometry={nodes['Cylinder050_plastic-main-2_0'].geometry}
          material={materials['plastic-main-2']}
        />
        <mesh
          geometry={nodes['Cylinder050_plastic-dark_0'].geometry}
          material={materials['plastic-dark']}
        />
      </a.group>
      <a.group position={[0, 8.254, -0.999]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes['Cylinder051_plastic-main_0'].geometry}
          material={materials['plastic-main']}
        />
        <mesh
          geometry={nodes['Cylinder051_plastic-secondary_0'].geometry}
          material={materials['plastic-secondary']}
        />
        <mesh
          geometry={nodes['Cylinder051_plastic-dark_0'].geometry}
          material={materials['plastic-dark']}
        />
      </a.group>
      <a.group
        position={[24.618, -5.186, -140.669]}
        rotation={[-0.154, -0.26, -0.04]}
        scale={[100, 100, 56.624]}>
        <mesh
          geometry={nodes['Cylinder053_plastic-secondary_0'].geometry}
          material={materials['plastic-secondary']}
        />
        <mesh
          geometry={nodes['Cylinder053_plastic-accent_0'].geometry}
          material={materials['plastic-accent']}
        />
        <mesh
          geometry={nodes['Cylinder053_plastic-accent-2_0'].geometry}
          material={materials['plastic-accent-2']}
        />
      </a.group>
      <a.group position={[-137.175, 19.463, -50.95]} rotation={[-1.578, 0.049, -0.313]} scale={100}>
        <mesh
          geometry={nodes['Cylinder056_plastic-secondary_0'].geometry}
          material={materials['plastic-secondary']}
        />
        <mesh
          geometry={nodes['Cylinder056_plastic-dark_0'].geometry}
          material={materials['plastic-dark']}
        />
        <mesh
          geometry={nodes['Cylinder056_plastic-accent-2_0'].geometry}
          material={materials['plastic-accent-2']}
        />
        <mesh
          geometry={nodes['Cylinder056_plastic-accent_0'].geometry}
          material={materials['plastic-accent']}
        />
      </a.group>
      <a.group
        position={[-22.943, -5.646, -143.745]}
        rotation={[-0.149, 0.133, 0]}
        scale={[100, 100, 56.624]}>
        <mesh
          geometry={nodes['Cylinder058_plastic-secondary_0'].geometry}
          material={materials['plastic-secondary']}
        />
        <mesh
          geometry={nodes['Cylinder058_plastic-accent_0'].geometry}
          material={materials['plastic-accent']}
        />
        <mesh
          geometry={nodes['Cylinder058_plastic-accent-2_0'].geometry}
          material={materials['plastic-accent-2']}
        />
      </a.group>
      <a.group
        position={[0.838, -5.9, -145.439]}
        rotation={[-0.149, -0.042, 0]}
        scale={[100, 100, 56.624]}>
        <mesh
          geometry={nodes['Cylinder059_plastic-secondary_0'].geometry}
          material={materials['plastic-secondary']}
        />
        <mesh
          geometry={nodes['Cylinder059_plastic-accent_0'].geometry}
          material={materials['plastic-accent']}
        />
        <mesh
          geometry={nodes['Cylinder059_plastic-accent-2_0'].geometry}
          material={materials['plastic-accent-2']}
        />
      </a.group>
      <a.group
        position={[145.574, -205.353, 142.586]}
        rotation={[-Math.PI / 2, 0, 0.786]}
        scale={100}>
        <mesh
          geometry={nodes['Sphere003_plastic-secondary_0'].geometry}
          material={materials['plastic-secondary']}
        />
        <mesh
          geometry={nodes['Sphere003_dark-metall_0'].geometry}
          material={materials['dark-metall']}
        />
        <mesh
          geometry={nodes.Sphere003_chrome_0.geometry}
          material={materials.chrome}
        />
      </a.group>
      <a.group position={[145.05, -205.353, -143.119]} rotation={[-Math.PI / 2, 0, 2.34]} scale={100}>
        <mesh
          geometry={nodes['Sphere011_plastic-secondary_0'].geometry}
          material={materials['plastic-secondary']}
        />
        <mesh
          geometry={nodes['Sphere011_dark-metall_0'].geometry}
          material={materials['dark-metall']}
        />
        <mesh
          geometry={nodes.Sphere011_chrome_0.geometry}
          material={materials.chrome}
        />
      </a.group>
      <a.group
        position={[-139.408, -205.353, -148.62]}
        rotation={[-Math.PI / 2, 0, -2.397]}
        scale={100}>
        <mesh
          geometry={nodes['Sphere014_plastic-secondary_0'].geometry}
          material={materials['plastic-secondary']}
        />
        <mesh
          geometry={nodes['Sphere014_dark-metall_0'].geometry}
          material={materials['dark-metall']}
        />
        <mesh
          geometry={nodes.Sphere014_chrome_0.geometry}
          material={materials.chrome}
        />
      </a.group>
      <a.group position={[-120.344, -126.146, 183.69]} rotation={[2.228, -0.484, -2.069]} scale={100}>
        <mesh
          geometry={nodes['Sphere017_plastic-secondary_0'].geometry}
          material={materials['plastic-secondary']}
        />
        <mesh
          geometry={nodes['Sphere017_dark-metall_0'].geometry}
          material={materials['dark-metall']}
        />
        <mesh
          geometry={nodes.Sphere017_chrome_0.geometry}
          material={materials.chrome}
        />
      </a.group>
      <a.group position={[0, 177.334, 0]} rotation={[-Math.PI / 2, 0, -0.494]} scale={100}>
        <mesh
          geometry={nodes['Sphere021_chrome-light_0'].geometry}
          material={materials['chrome-light']}
        />
        <mesh
          geometry={nodes['Sphere021_dark-metall_0'].geometry}
          material={materials['dark-metall']}
        />
      </a.group>
      <mesh
        geometry={nodes['Circle_dark-metall_0'].geometry}
        material={materials['dark-metall']}
        position={[-136.927, 18.428, -50.87]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes['Cube011_dark-metall_0'].geometry}
        material={materials['dark-metall']}
        position={[-25.902, -10.15, 99.674]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[7.945, 7.945, 35.457]}
      />
      <mesh
        geometry={nodes.Cylinder007_chrome_0.geometry}
        material={materials.chrome}
        position={[0, -95.407, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[45.66, 45.66, 26.343]}
      />
      <mesh
        geometry={nodes['Cylinder009_plastic-main_0'].geometry}
        material={materials['plastic-main']}
        position={[133.975, -162.902, 131.205]}
        rotation={[-1.979, -0.383, 0.712]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder010_chrome_0.geometry}
        material={materials.chrome}
        position={[57.575, -186.852, 55.358]}
        rotation={[-Math.PI, 0.779, 1.895]}
        scale={[12.087, 12.087, 4.91]}
      />
      <mesh
        geometry={nodes['Cylinder015_plastic-main_0'].geometry}
        material={materials['plastic-main']}
        position={[133.473, -162.902, -131.716]}
        rotation={[-1.164, -0.384, 2.426]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder016_chrome_0.geometry}
        material={materials.chrome}
        position={[56.333, -186.852, -56.621]}
        rotation={[-Math.PI, -0.775, 1.895]}
        scale={[12.087, 12.087, 4.91]}
      />
      <mesh
        geometry={nodes['Cylinder021_plastic-main_0'].geometry}
        material={materials['plastic-main']}
        position={[-128.301, -162.902, -136.759]}
        rotation={[-1.147, 0.365, -2.471]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder022_chrome_0.geometry}
        material={materials.chrome}
        position={[-55.18, -186.852, -57.746]}
        rotation={[0, -0.821, -1.247]}
        scale={[12.087, 12.087, 4.91]}
      />
      <mesh
        geometry={nodes['Cylinder036_plastic-main_0'].geometry}
        material={materials['plastic-main']}
        position={[-127.407, -156.492, 150.594]}
        rotation={[2.479, 0.013, -2.003]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder037_chrome_0.geometry}
        material={materials.chrome}
        position={[-54.423, -186.852, 58.46]}
        rotation={[0, 0.808, -1.247]}
        scale={[12.087, 12.087, 4.91]}
      />
      <mesh
        geometry={nodes.Cylinder057_chrome_0.geometry}
        material={materials.chrome}
        position={[-134.619, 41.994, -52.316]}
        rotation={[-1.578, 0.049, -0.313]}
        scale={[49.278, 49.278, 73.13]}
      />
      <mesh
        geometry={nodes['finger003_dark-metall_0'].geometry}
        material={materials['dark-metall']}
        position={[169.082, -229.137, 166.156]}
        rotation={[-Math.PI, 0.784, Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes['finger004_dark-metall_0'].geometry}
        material={materials['dark-metall']}
        position={[151.7, -229.137, 112.523]}
        rotation={[Math.PI, -1.416, Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes['finger005_dark-metall_0'].geometry}
        material={materials['dark-metall']}
        position={[115.631, -229.137, 149.402]}
        rotation={[0, 0.182, -Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes['finger006_dark-metall_0'].geometry}
        material={materials['dark-metall']}
        position={[169.018, -229.137, -166.221]}
        rotation={[Math.PI, -0.769, Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes['finger007_dark-metall_0'].geometry}
        material={materials['dark-metall']}
        position={[115.096, -229.137, -149.757]}
        rotation={[0, -0.172, -Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes['finger008_dark-metall_0'].geometry}
        material={materials['dark-metall']}
        position={[151.355, -229.137, -113.064]}
        rotation={[-Math.PI, 1.406, Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes['finger009_dark-metall_0'].geometry}
        material={materials['dark-metall']}
        position={[-161.897, -229.137, -173.165]}
        rotation={[0, -0.827, -Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes['finger010_dark-metall_0'].geometry}
        material={materials['dark-metall']}
        position={[-146.801, -229.137, -118.843]}
        rotation={[0, 1.374, -Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes['finger011_dark-metall_0'].geometry}
        material={materials['dark-metall']}
        position={[-109.203, -229.137, -154.163]}
        rotation={[-Math.PI, -0.14, Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes['finger012_dark-metall_0'].geometry}
        material={materials['dark-metall']}
        position={[-139.573, -100.865, 230.865]}
        rotation={[-2.24, -0.458, 0.391]}
        scale={100}
      />
      <mesh
        geometry={nodes['finger013_dark-metall_0'].geometry}
        material={materials['dark-metall']}
        position={[-102.182, -77.532, 167.271]}
        rotation={[2.035, 1.09, 1.542]}
        scale={100}
      />
      <mesh
        geometry={nodes['finger014_dark-metall_0'].geometry}
        material={materials['dark-metall']}
        position={[-71.12, -128.529, 207.698]}
        rotation={[0.427, -0.411, 2.461]}
        scale={100}
      />
      <mesh
        geometry={nodes.Sphere001_chrome_0.geometry}
        material={materials.chrome}
        position={[117.525, -129.197, 114.908]}
        rotation={[-1.86, -0.281, 0.745]}
        scale={24.272}
      />
      <mesh
        geometry={nodes.Sphere002_chrome_0.geometry}
        material={materials.chrome}
        position={[145.494, -192.499, 142.507]}
        rotation={[-1.671, -0.101, 0.781]}
        scale={23.768}
      />
      <mesh
        geometry={nodes.Sphere004_chrome_0.geometry}
        material={materials.chrome}
        position={[116.897, -129.197, -115.547]}
        rotation={[-1.283, -0.282, 2.381]}
        scale={24.272}
      />
      <mesh
        geometry={nodes.Sphere005_chrome_0.geometry}
        material={materials.chrome}
        position={[0.003, -6.726, 115.305]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={30.506}
      />
      <mesh
        geometry={nodes['Sphere007_glass-orange_0'].geometry}
        material={materials['glass-orange']}
        position={[0, 177.334, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Sphere010_chrome_0.geometry}
        material={materials.chrome}
        position={[144.97, -192.499, -143.04]}
        rotation={[-1.471, -0.101, 2.345]}
        scale={23.768}
      />
      <mesh
        geometry={nodes.Sphere012_chrome_0.geometry}
        material={materials.chrome}
        position={[-112.556, -129.197, -119.78]}
        rotation={[-1.271, 0.269, -2.438]}
        scale={24.272}
      />
      <mesh
        geometry={nodes.Sphere013_chrome_0.geometry}
        material={materials.chrome}
        position={[-139.331, -192.499, -148.538]}
        rotation={[-1.467, 0.096, -2.402]}
        scale={23.768}
      />
      <mesh
        geometry={nodes.Sphere015_chrome_0.geometry}
        material={materials.chrome}
        position={[-125.589, -180.821, 119.217]}
        rotation={[2.121, -0.638, -2.119]}
        scale={24.272}
      />
      <mesh
        geometry={nodes.Sphere016_chrome_0.geometry}
        material={materials.chrome}
        position={[-126.238, -135.154, 176.666]}
        rotation={[2.3, -0.358, -2.04]}
        scale={23.768}
      />
      <mesh
        geometry={nodes.Sphere020_eyes_0.geometry}
        material={materials.eyes}
        position={[0.003, -6.726, 115.305]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes['Sphere022_sirena-lights_0'].geometry}
        material={materials['sirena-lights']}
        position={[0, 177.334, 0]}
        rotation={[-Math.PI / 2, 0, -0.494]}
        scale={100}
      />
      <mesh
        geometry={nodes['Torus002_chrome-light_0'].geometry}
        material={materials['chrome-light']}
        position={[0.003, -6.726, 115.305]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Sphere006_glass_0.geometry}
        material={materials.glass}
        position={[0.003, -6.726, 115.305]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Sphere_glass_0.geometry}
        material={materials.glass}
        position={[0.003, -6.726, 115.305]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </a.group>
  )
}

export default PoliceR
